### PR TITLE
Fixes/950 single submission link

### LINKED ISSUE #950: Enketo is enabled - Single Submission Public link doesn't work
Example: See "Single" public link at https://staging.getodk.cloud/projects/18/forms/ses2018/public-links

~Potential cause: `st` query parameter has `!`~ This can still be true, but we need to fix the following issue first.

Root cause: enketoOnceId is incorrect - [notes](https://docs.google.com/document/d/1AzOaax9xszZt32fJ1kh2LlGIT--KQO4PRECC3t30VEc/edit?tab=t.0#heading=h.mftcbgagpm3f)

### PR DESCRIPTION
**Pull request by sadiqkhoja**
Part of #950 

**Background**
For Single Submission links, Enketo’s frontend sets a cookie upon successful submission. The cookie has the format `enketoOnceId=timestamp_of_submission` and is scoped to the path /-/single.

However, since we now serve the Enketo Form from /enketo-passthrough, the cookie is no longer sent to the server, which prevents it from enforcing single submissions.

To fix this, we have added a dummy location /-/single/check-submitted in the Nginx configuration. The Central frontend loads this location in a hidden iframe and checks for the presence of the cookie with `<enketoOnceId>` key. If the cookie is found, the user is redirected to the thank-you page.

#### Before submitting this PR, please make sure you have:

- [x] branched off and targeted the `next` branch OR only changed documentation/infrastructure (`master` is stable and used in production)
- [x] verified that any code or assets from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

File: test/nginx/test-nginx.js [hunk 1]
```diff
@@ -156,6 +156,15 @@ describe('nginx config', () => {
     });
   });
 
+  it('should serve blank page on /-/single/check-submitted', async () => {
+    // when
+    const res = await fetchHttps('/-/single/check-submitted');
+
+    // then
+    assert.equal(res.status, 200);
+    assert.isEmpty((await res.text()).trim());
```
Comment (matthew-white) [inline test/nginx/test-nginx.js:165]: Shouldn't `res.text()` include the HTML? Or does `res.text()` only return the inner content of the `<body>` element? Is there a way for the test to verify that blank.html is being served?

File: test/nginx/test-nginx.js [hunk 2]
```diff
@@ -156,6 +156,15 @@ describe('nginx config', () => {
     });
   });
 
+  it('should serve blank page on /-/single/check-submitted', async () => {
+    // when
+    const res = await fetchHttps('/-/single/check-submitted');
+
+    // then
```
Comment (matthew-white) [inline test/nginx/test-nginx.js:163]: How about also asserting:

```js
await assertEnketoReceivedNoRequests();
```

File: files/nginx/odk.conf.template [hunk 3]
```diff
@@ -65,6 +65,11 @@ server {
     # Form fill link (non-public), or Draft
     return 301 "/f/$enketoId/new$is_args$args";
   }
+  # To read single submission cookies
+  location = /-/single/check-submitted {
+      alias /usr/share/nginx/html/blank.html;
+      default_type text/html;
```
Comment (matthew-white) [inline files/nginx/odk.conf.template:71]: It looks like this is indented by 4 spaces rather than 2.

**Review by matthew-white — APPROVED** [review]
The change to the nginx config here matches the change in getodk/central-frontend#1186, which I also reviewed.

File: test/nginx/test-nginx.js (hunk 1 above)
Comment (sadiqkhoja) [reply test/nginx/test-nginx.js:165]: When `SKIP_FRONTEND_BUILD` is true, then `build-frontend.sh` creates an empty blank.html
