### PR TITLE
Defend against systems with no memory.max

### LINKED ISSUE #1181: If /sys/fs/cgroup/memory.max doesn’t exist, Central crashes.
I don't know how common this is, but this is a from server that was stuck in a crash loop. Things were going well, then something send SIGTERMS from outside the container. Central couldn't come back up because it couldn't find `/sys/fs/cgroup/memory.max` and thus set an absurd memory limit (9223372036854771712).

We should to see if the file exists before trying to read it. Bonus points if we also check if memtot is non-empty and numeric before using it.

```
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:18 +0000] "GET /v1/key/Foo/projects/5/formList HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:18 +0000] "GET /v1/key/Foo/projects/18/formList HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:18 +0000] "GET /v1/key/Foo/projects/5/forms/BAR_F01_ENROLLMENT_P2/manifest HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:18 +0000] "GET /v1/key/Foo/projects/5/forms/BAR_F02_INFECTEPISODE_P2_0/manifest HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:18 +0000] "GET /v1/key/Foo/projects/5/forms/BAR_F03_INFECTION_HOSPITAL_OUTCOME_P2_0/manifest HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:19 +0000] "GET /v1/key/Foo/projects/18/formList HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:19 +0000] "GET /v1/key/Foo/projects/5/forms/BAR_F04_D28_FIN_P2_0/manifest HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:19 +0000] "GET /v1/key/Foo/projects/5/forms/BAR_F05_BSI_FIN_P2_0/manifest HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:51:19 +0000] "GET /v1/key/Foo/projects/5/forms/BAR_F06_HAIWARD_FIN_P2_0/manifest HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:56:41 +0000] "GET /v1/key/Foo/projects/19/formList HTTP/1.0" 200 107
::ffff:172.18.0.3 - - [20/Jul/2025:23:56:42 +0000] "GET /v1/key/Foo/projects/19/formList HTTP/1.0" 200 107
::ffff:172.18.0.3 - - [20/Jul/2025:23:56:42 +0000] "GET /v1/key/Foo/projects/19/formList HTTP/1.0" 304 -
::ffff:172.18.0.3 - - [20/Jul/2025:23:56:42 +0000] "GET /v1/key/Foo/projects/19/formList HTTP/1.0" 200 107
npm error path /usr/odk
npm error command failed
npm error signal SIGTERM
npm error command sh -c pm2-runtime ./pm2.config.js
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.4.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.4.2
npm notice To update run: npm install -g npm@11.4.2
npm notice
npm error A complete log of this run can be found in: /root/.npm/_logs/2025-07-09T00_04_33_343Z-debug-0.log
wait-for-it: waiting 15 seconds for postgres14:5432
wait-for-it: postgres14:5432 is available after 0 seconds
generating local service configuration..
running migrations..
starting cron..
using 4 worker(s) based on available memory (9223372036854771712)..
starting server.
2025-07-20T23:58:11: PM2 log: Launching in no daemon mode
2025-07-20T23:58:12: PM2 log: App [service:0] starting in -cluster mode-
2025-07-20T23:58:12: PM2 log: App [service:0] online
2025-07-20T23:58:12: PM2 log: App [service:1] starting in -cluster mode-
2025-07-20T23:58:12: PM2 log: App [service:1] online
2025-07-20T23:58:12: PM2 log: App [service:2] starting in -cluster mode-
2025-07-20T23:58:12: PM2 log: App [service:2] online
2025-07-20T23:58:12: PM2 log: App [service:3] starting in -cluster mode-
2025-07-20T23:58:12: PM2 log: App [service:3] online
npm error path /usr/odk
npm error command failed
npm error signal SIGTERM
npm error command sh -c pm2-runtime ./pm2.config.js
npm notice
npm notice New major version of npm available! 10.9.2 -> 11.4.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.4.2
npm notice To update run: npm install -g npm@11.4.2
npm notice
npm error A complete log of this run can be found in: /root/.npm/_logs/2025-07-20T23_58_06_735Z-debug-0.log
wait-for-it: waiting 15 seconds for postgres14:5432
wait-for-it: postgres14:5432 is available after 1 seconds
generating local service configuration..
running migrations..
starting cron..
cat: /sys/fs/cgroup/memory.max: No such file or directory
wait-for-it: waiting 15 seconds for postgres14:5432
wait-for-it: postgres14:5432 is available after 0 seconds
generating local service configuration..
running migrations..
starting cron..
cat: /sys/fs/cgroup/memory.max: No such file or directory
wait-for-it: waiting 15 seconds for postgres14:5432
wait-for-it: postgres14:5432 is available after 0 seconds
generating local service configuration..
running migrations..
starting cron..
cat: /sys/fs/cgroup/memory.max: No such file or directory
wait-for-it: waiting 15 seconds for postgres14:5432
wait-for-it: postgres14:5432 is available after 0 seconds
generating local service configuration..
running migrations..
starting cron..
```

### LINKED ISSUE #1603: start-odk.sh fails if /sys/fs/cgroup/memory/memory.limit_in_bytes is missing
Ubuntu 22.04.5, which has cgroup2fs enabled, does not have a /sys/fs/cgroup/memory/memory.limit_in_bytes file. It also doesn't have /sys/fs/cgroup/memory.max (but that is expected since it's not cgroup v1).

Without this memory, Central goes into a boot loop.

```
root@server:~/central# cat /etc/lsb-release  | grep _RELEASE
DISTRIB_RELEASE=22.04

root@server:~/central# stat -fc %T /sys/fs/cgroup/
cgroup2fs

root@server:~/central# cat /sys/fs/cgroup/memory.max
cat: /sys/fs/cgroup/memory.max: No such file or directory

root@server:~/central# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
cat: /sys/fs/cgroup/memory/memory.limit_in_bytes: No such file or directory

root@server:~/central# grep MemTotal /proc/meminfo | awk '{print $2 * 1024}'
2003337216
```

### PR DESCRIPTION
**Pull request by yanokwa**
Fixes #1603 
Fixes #1181 

Tried to make the most narrow change possible: check for the necessary file and fall back to using all memory if the file is missing.

### CODE REVIEW

**Comment by alxndrsn** [comment]
Looks like there's more context at:

* https://github.com/getodk/central/pull/876
* 4ea08220e22d91fb262e9c61c2e8718aab7fc435

File: files/service/scripts/start-odk.sh [hunk 1]
```diff
@@ -39,25 +39,30 @@ get_cgroup_version() {
 }
 
 get_memory_limit() {
-  local cgroup_version
+  local cgroup_version memtot fallback_memtot
   cgroup_version=$(get_cgroup_version)
+  fallback_memtot=$(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')
```
Comment (alxndrsn) [inline files/service/scripts/start-odk.sh]: What happens if `/proc/meminfo` is unreadable?

File: files/service/scripts/start-odk.sh
Comment (alxndrsn) [inline files/service/scripts/start-odk.sh:74]: Would this be safer?

```suggestion
MEMTOT=$(get_memory_limit || echo "unknown")
```

This should do something like:

```sh
...
grep: /proc/meminfo: Permission denied
using 1 worker(s) based on available memory (0)..
```

Comment (alxndrsn) [reply files/service/scripts/start-odk.sh:74]: If looking for the most narrow change possible I suspect this is it.

File: files/service/scripts/start-odk.sh (hunk 1 above)
Comment (yanokwa) [reply files/service/scripts/start-odk.sh]: Updated to set fallback to 0 in that case.

File: files/service/scripts/start-odk.sh
Comment (yanokwa) [reply files/service/scripts/start-odk.sh:74]: I've now also simplified cgroup detection.
